name: Docker Image CI

on:
  pull_request:
    branches:
      - develop

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install modules
        run: cd client && npm ci

      # # ESLint and Prettier must be in `package.json`
      # - name: Install Node.js dependencies
      #   run: cd client && npm ci

      # - name: Set up .NET
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: "6.0.x"

      - name: Run ESLint
        # run: cd client && npm run check-all
        run: cd client && npm run check-lint

      # - name: Run Lint Action
      #   uses: wearerequired/lint-action@v2
      #   with:
      #     eslint: true
      #     prettier: true

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create backend env file
        run: cp .env.api.example .env.api

      - name: Create frontend env file
        run: cp .env.client.example .env.client

      - name: Create db env file
        run: cp .env.db.example .env.db

      - name: Build the Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker compose build
